name: update development vm

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_DEV_HOST }}
          username: ${{ secrets.VM_DEV_USER }}
          key: ${{ secrets.VM_DEV_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/projects/snippet-infrastructure
            sudo docker compose pull
            sudo docker compose up -d
